name: Publish Package to npm

# on:
#   push:
#     branches:
#       - main
#       - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node (v20 LTS)
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Bump version (main or dev)
        id: bump
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          if [ "$BRANCH_NAME" = "main" ]; then
            npm version patch --no-git-tag-version
          elif [ "$BRANCH_NAME" = "dev" ]; then
            npm version prerelease --preid=beta --no-git-tag-version
          fi
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Publish to npm
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          if [ "$BRANCH_NAME" = "main" ]; then
            npm publish
          elif [ "$BRANCH_NAME" = "dev" ]; then
            npm publish --tag beta
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add package.json package-lock.json
          git commit -m "chore(release): v$VERSION"
          git tag v$VERSION
          git push origin v$VERSION
